float:
  any:
    - base_args: ["@metric"]
      constructor: Qdrant
      disabled: False
      docker_tag: bigvectorbench-qdrant
      module: bigvectorbench.algorithms.qdrant
      name: qdrant
      run_groups:
        HNSW:
          args:
            M: [4, 8, 12, 16, 24, 36, 48, 64, 96]
            efConstruction: [200, 500]
          query_args: [
              [100, 120, 150, 200, 500, 600, 800], #hnsw_ef
              [True, False], # re-score
            ]
